unbind r
bind r source-file ~/.config/tmux/tmux.conf

set -g default-terminal "screen-256color"
set -g prefix C-p
unbind C-b
bind-key C-p send-prefix

unbind %
bind | split-window -h
bind-key -n S-left previous-window
bind-key -n S-right next-window

unbind '"'
bind - split-window -v
#Act like VIM
# set -g mode-keys vi

#
#Full screen?
bind -r m resize-pane -Z


set -g mouse on

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'hoshiya4522/tokyo-night-tmux'
# set -g @plugin 'catppuccin/tmux'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-sidebar'
set -g @plugin 'tmux-plugins/tmux-sessionist'
set -g @plugin 'tmux-plugins/tmux-prefix-highlight'
set -g @plugin 'tmux-plugins/tmux-fpp'
#set -g @plugin 'erikw/tmux-powerline'
#
set -g @resurrect-capture-pane-contents 'on'
set -g @continuum-restore 'on'
#
#
## Dracula Theme
## set -g @plugin 'dracula/tmux'
## set -g @dracula-plugins "git attached-clients time weather"
## available colors: white, gray, dark_gray, light_purple, dark_purple, cyan, green, orange, red, pink, yellow
## set -g @dracula-[plugin-name]-colors "[background] [foreground]"
## set -g @dracula-cpu-usage-colors "pink dark_gray"
## set -g @dracula-show-powerline true
## set -g @dracula-show-left-sep 
## set -g @dracula-show-left-sep |
## set -g @dracula-show-right-sep 
## set -g @dracula-show-right-sep |
## set -g @dracula-show-flags true
## set -g @dracula-refresh-rate 1
## set -g @dracula-border-contrast true
## set -g @dracula-show-empty-plugins false
## set -g @dracula-show-timezone false
## set -g @dracula-fixed-location "Nairobi"
## set -g @dracula-show-fahrenheit false
## set -g @dracula-git-disable-status true
## set -g @dracula-git-show-current-symbol ✓
## set -g @dracula-git-show-diff-symbol !
## set -g @dracula-git-no-repo-message ""
## set -g @dracula-git-no-untracked-files true
## set -g @dracula-git-show-remote-status true
set -g status-position bottom
#
#
#
#
#
run '~/.config/tmux/plugins/tpm/tpm'

